swagger: '2.0'
info:
  version: 1.0.0
  title: Product
  contact:
    name: Apigee
    email: support@apigee.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: product.apigee.net
basePath: /v1/products
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      summary: Get all products
      description: This endpoint returns a list of all products as an array.
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProductsArray'
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    post:
      summary: Create a new Product
      description: This endpoint will create a new Product.
      parameters:
        - name: body
          required: true
          description: an product oject
          in: body
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/{product_id}':
    get:
      summary: Get a Product with given UUID.
      description: This endpoint returns a Product from a given UUID.
      parameters:
        - name: product_id
          in: path
          required: true
          description: UUID of a Product
          type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    put:
      summary: Update a Product with given UUID
      description: This endpoint will update an existing Product.
      parameters:
        - name: product_id
          in: path
          required: true
          description: UUID of a Product
          type: integer
        - name: body
          required: true
          description: an Product oject
          in: body
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    delete:
      summary: Delete a Product with given UUID
      description: This endpoint will delete an existing Product.
      parameters:
        - name: product_id
          in: path
          required: true
          description: UUID of a Product
          type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
definitions:
  ProductsArray:
    type: array
    items:
      type: object
      properties:
        uuid:
          type: string
        type:
          type: string
        name:
          type: string
        created:
          type: integer
        modified:
          type: integer
        birthDate:
          type: string
        city:
          type: string
        department:
          type: string
        email:
          type: string
        gender:
          type: string
        isActive:
          type: boolean
        metadata:
          type: object
          properties:
            path:
              type: string
            size:
              type: integer
        phone:
          type: string
        postal:
          type: integer
        state:
          type: string
        street:
          type: string
  Product:
    type: object
    properties:
      uuid:
        type: string
      type:
        type: string
      name:
        type: string
      created:
        type: integer
      modified:
        type: integer
      birthDate:
        type: string
      city:
        type: string
      department:
        type: string
      email:
        type: string
      gender:
        type: string
      isActive:
        type: boolean
      metadata:
        type: object
        properties:
          path:
            type: string
          size:
            type: integer
      phone:
        type: string
      postal:
        type: integer
      state:
        type: string
      street:
        type: string
