swagger: "2.0"
info:
  version: "1.0.0"
  title: Swagger API
host: localhost
basePath: /cognizant/sample
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /cognizant/sample:
    get:
      description: Returns greetings to the caller
      operationId: cognizant-sample
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/sample"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  sample:
    required:
      - message
    properties:
      message:
        type: string
      age:
        type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string